CFLAGS=-g -ggdb -g3 -Wall
CC=gcc
BIN=./bin/
EXECUTABLE=test_list

#
# Link
#

bin/test_list: 
# To be completed

#
# Objets of TP Lists
#

obj/list.o: obj
	$(CC) $(CFLAGS) -c -o $@ $< 
# To be completed
obj/test_list.o: obj
	$(CC) $(CFLAGS) -c -o $@ $< 
# To be completed

#
# Listing creation in pdf
#

listing:
# To be completed

#
# Remove files
#

clean :
# To be completed

#
# Test the functionality 
#

test :


obj:
	mkdir ./obj
